export const exampleText = `
In the Pride Lands of Tanzania, a pride of lions rules over the kingdom from Pride Rock. As the sun rises over the Pride Lands, King Mufasa and Queen Sarabi's newborn son, Prince Simba, is presented to the gathered animals by Rafiki, the mandrill who serves as the kingdom's shaman and advisor. However, Mufasa's younger brother, Scar, covets the throne and secretly plots to eliminate both Mufasa and Simba so that he may become king.

When Simba grows into a young cub, Mufasa shows him the Pride Lands and explains to Simba the responsibilities of kingship and the "circle of life," which connects all living things. But then Scar manipulates Simba into exploring an elephants' graveyard beyond the Pride Lands, which Mufasa forbade him to do so, stating that only the bravest lions go there. Wanting to prove his courage, Simba escapes Mufasa's majordomo, the hornbill Zazu and sneaks into the elephants' graveyard along with his best friend, Nala, though Zazu catches up to them. Upon arriving, however, the trio is chased by three spotted hyenas named Shenzi, Banzai and Ed. Zazu manages to alert Mufasa, and he arrives to chase the hyenas away. Though disappointed in Simba for disobeying him and endangering himself and Nala, Mufasa forgives him while teaching him the importance of bravery. He then explains that the great kings of the past watch over them from the night sky, from which he will one day watch over Simba. Meanwhile, Scar, who had orchestrated the hyenas' attack, convinces them to help him murder Mufasa and Simba in exchange for hunting rights in the Pride Lands.

The next day, Scar lures Simba into a gorge and signals the hyenas to drive a large herd of wildebeests into a stampede to trample him. Scar alerts Mufasa, who manages to save Simba and tries to escape the gorge; he begs Scar for help, but Scar betrays him by throwing him into the stampede to his death. Scar then deceives Simba into believing that Mufasa's death was his fault and tells him to leave the Pride Lands into exile and never return. He then orders the hyenas to kill Simba, but Simba escapes, and they decide not to tell him of it. Unaware of Simba's survival, Scar tells the pride that both Mufasa and Simba are dead, and steps forward as the new king, allowing the hyenas into the Pride Lands, much to the shock of the pride and the sadness of Rafiki.

Simba collapses in a desert from heat exhaustion, but is rescued by two other outcasts; a meerkat and a warthog named Timon and Pumbaa. Simba grows up with his two new friends in their jungle oasis, living a carefree life under their motto "hakuna matata" ("no worries" in Swahili). Years later, a young adult Simba rescues Timon and Pumbaa from a hungry lioness, who is revealed to be Nala. After reconciling, Simba and Nala end up falling in love, and she urges him to return home, telling him that the Pride Lands have become a desolate wasteland under Scar's reign. Still feeling guilty over Mufasa's death, Simba refuses and leaves angrily. He then encounters Rafiki, who tells Simba that Mufasa’s spirit lives on in him. Simba is then visited by the spirit of Mufasa in the night sky, who tells him that he must take his place as king. After Rafiki advises him to learn from the past instead of running from it, Simba decides to return to the Pride Lands.

Aided by his friends, Simba sneaks past the hyenas at Pride Rock and confronts Scar, who shames Simba over his supposed role in Mufasa’s death and corners him to the edge of Pride Rock. Just before he could throw him into a fire created by lightning, Scar arrogantly reveals to Simba that he killed Mufasa. Enraged, Simba retaliates and forces Scar to confess the truth to the pride. A battle ensues between the pride and the hyenas. Scar attempts to escape but is cornered by Simba at a ledge near the top of Pride Rock. Scar begs for mercy and attempts to deceive Simba by blaming his actions on the hyenas, who overhear him. Simba refuses to believe him, but spares Scar's life while banishing him from the Pride Lands forever. Scar pretends to accept this, but then attacks Simba. Following a brief battle, Simba throws Scar off the ledge. Scar survives the fall, but the hyenas, angry at him for betraying them, attack and maul him to his death.

With Scar and the hyenas gone, Simba takes his rightful place as king, with Nala as his queen. With the Pride Lands restored, Rafiki presents Simba and Nala's newborn cub to the assembled animals, thus continuing the circle of life.
`;
